### ISSUE TITLE
Sorry but you gave us preinstalled Adware. You can't remove that from our brains.

### ISSUE THREAD

**Issue by Horrgs** [lenovo-inc/superfishremoval#1] opened 2015-02-21 08:01 UTC
P.S.: I go to a private high school that gives each student a Lenovo laptop. Not sure if Adware is on it, not my issue. 

Our contract with whoever ends over the summer so we'll be get getting new ones. My teacher that knows the most about technology and handles the laptops, etc,. said we can only get Lenovo's as they are the "best" built laptops. I told him "Where did you hear that? Answers.com?" (Answers.com is also an inside joke because a student used it as a source for a research paper we're doing haha). Took 90% off my paper for calling him out and turning it in 20 minutes late. 

Wonder what his  opinion will be on this and can you tell him I deserve 180% bc pre-installing Adware on our computers obviously proves you aren't the best "built" laptops.

**Comment by MitchK** [comment] 2015-02-21 15:29
:+1:

**Comment by tauheedul** [comment] 2015-02-21 17:52
It's an expensive mistake by Lenovo... I'm glad they've responded quickly. They're not the only brand to include adware with their consumer laptops, other manufacturers have done it for years. The mistake was not vetting their partners products more rigorously. It's gonna cost them in sales and time to mend their reputation. Let's see if the other manufacturers do the same.

**Comment by vadi2** [comment] 2015-02-23 06:54
Well, they started off by creating a tool to remove it and open-sourced it so people have no doubts about it - I think that is a good start.

**Comment by Sandy1973** [comment] 2015-02-23 06:57
Choshsteinhauey jew tant phooling mesh

**Comment by jag426** [comment] 2015-02-23 08:44
This isn't an issue with this project. Save it for Reddit.

**Comment by lenovo-inc** [comment] 2015-02-23 17:35
Duplicate of #11

**Closed by lenovo-inc** 2015-02-23 17:35 UTC
